### ISSUE TITLE
`ARGO_LOG_LEVEL` has no effect

### ISSUE THREAD

**Issue by juliev0** [kitproj/kit#41]
If I set:
```
- name: controller
  env:
    - ARGO_LOG_LEVEL=debug
```

in argo-workflows' tasks.yaml file, it seems to have no effect. (I haven't tried the other environment variables.)

**Comment by alexec** [comment]
WFM? 

Can you try this:

```yaml
apiVersion: kit/v1
kind: Tasks
metadata:
  name: kit
spec:
  semaphores:
    two: 2
  tasks:
  - name: test
    command: sh -c "echo $FOO"
    env:
      - FOO=bar
```

```bash
CI=1 kit test
```
